apiVersion: v1
kind: Service
metadata:
  name: devops-info-service-v2
  labels:
    app: devops-info-service-v2
spec:
  type: NodePort
  selector:
    app: devops-info-service-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30081
